---
- project:
    templates:
      - publish-stx-docs
      - stx-release-notes-jobs
      - stx-bandit-jobs
    check:
      jobs:
        - openstack-tox-linters
        - stx-distcloud-client-tox-pep8
        - stx-distcloud-client-tox-py39
        - stx-distcloud-client-tox-pylint
        - stx-distcloud-client-tox-black
        - stx-distcloud-client-tox-cover
    gate:
      jobs:
        - openstack-tox-linters
        - stx-distcloud-client-tox-pep8
        - stx-distcloud-client-tox-py39
        - stx-distcloud-client-tox-pylint
        - stx-distcloud-client-tox-black
        - stx-distcloud-client-tox-cover
    post:
      jobs:
        - stx-distcloud-client-upload-git-mirror

- job:
    name: stx-distcloud-client-tox-py39
    parent: tox-py39
    description: Run py39 for distcloud-client
    nodeset: debian-bullseye
    required-projects:
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: py39
      tox_extra_args: -c distributedcloud-client/tox.ini

- job:
    name: stx-distcloud-client-tox-pylint
    parent: tox
    description: Run pylint for distcloud-client
    nodeset: debian-bullseye
    required-projects:
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: pylint
      tox_extra_args: -c distributedcloud-client/tox.ini

- job:
    name: stx-distcloud-client-tox-pep8
    parent: tox
    description: Run pep8 for distcloud-client
    nodeset: debian-bullseye
    required-projects:
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: pep8
      tox_extra_args: -c distributedcloud-client/tox.ini

- job:
    name: stx-distcloud-client-tox-black
    parent: tox
    description: Run black for distcloud-client
    nodeset: debian-bullseye
    required-projects:
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: black_check
      tox_extra_args: -c distributedcloud-client/tox.ini

- job:
    name: stx-distcloud-client-tox-cover
    parent: tox
    description: Run coverage test for distcloud-client
    nodeset: debian-bullseye
    required-projects:
      - starlingx/utilities
    vars:
      python_version: 3.9
      tox_envlist: cover
      tox_extra_args: -c distributedcloud-client/tox.ini
    post-run: tools/gate/playbooks/fetch-coverage.yaml
    voting: false

- job:
    name: stx-distcloud-client-upload-git-mirror
    parent: upload-git-mirror
    description: >
      Mirrors opendev.org/starlingx/distcloud-client to
      github.com/starlingx/distcloud-client
    vars:
      git_mirror_repository: starlingx/distcloud-client
    secrets:
      - name: git_mirror_credentials
        secret: stx-distcloud-client-github-secret3
        pass-to-parent: true

- secret:
    name: stx-distcloud-client-github-secret3
    data:
      user: git
      host: github.com
      # yamllint disable-line rule:line-length
      host_key: github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk=
      ssh_key: !encrypted/pkcs1-oaep
        - LuMaqqNLzHb8MZKOw8q4sD2oKryUVlkMH6Z1mLcY+eAgEEEoRtj96KgxETHxGN94dmG8C
          6iSGp4ZpaFXY05BzkTKVSasrPfIvkm5fE7iGmmbNJd8+y3loVTXt0QFUyMamTMzoT1RO3
          KFc6f0GmUu+MpUP3VoFn9WhB0uUyKJRIEVxQteq0GFLSkFH5w56C6oH0oeZ1K6rGA+9RZ
          kShP1Xiq6w3W/ajKgmEj8Wkx1oMqqpUrtmxYXN8uhEW0h/CtNVmHEMJDEDs1mwEWLlHyx
          VmiEhg7L4FkO27n6RubST0uiXmshpoHxDCRAiMJ8OGrH3ZvhcPZ/baAZY3N5vpyQny1ZO
          M78msxTx9jLcokxBj0PulkindIazdd/eHBCX2bE5An8+WW/RkvN+75S0wPbxAiAo+s38z
          PCB+jX1+SApPVM4YHevl4M0rQsFI2PjNod4KOntOmKu9buO+UIWv+FiU5hxucL1N759lQ
          yj/3qA13rPip3ezC26sjbHGJEEKIZosGUYdv3ejlFDohhbXF1TRuOSOZclk6q6+afsB/C
          oj5FozaaijQWjQu8Fkh11S/smTi8ayIp2BJ1S3Z9KVySBm4/JsZnaIM2Or53LABdfp4Ov
          xOFC8trlXR67WV7klk54ZQl2LsyyCXfdDyFF8THknrTKFgzP3Ya8K1SKw5y1PM=
        - MVgqzC//ygrNLXRm85WqTdiMfRsAOHoDaTaKfn6HzgkoeOKVzh/2SiBenwzKHacJf2xCp
          SQf95LLzQYyJ5hkYuwUosDRZPS0n4aQMwuqLDEptJKU+hNgKHFyVg0jwOydS/uUjM5NLo
          1BMB6DMTp8MQ2/Vf585RSXcj1Gi4rtmLCrDeFa0ELDmgOZrBFTptCzM+x9yIuEvwrSbPl
          o/iCKSDm77/y504bHxHHHbYUIyO8OHvtKPP0nSVxN4R3q0VdzF05tZWjk/cK0rS38D6tq
          vKRlJrRPJvy3kPaTFYvi7xL+p/HAShTEQJ7Awzxd7oZm9DwhAAPTf/nN0BOKH3/e+atxY
          WxlrNjAIpW2n49v0cQU4MSlFD+pPhFO0YS0tU93AV44qqUoX2/+GGHGZIPuClVKxsZ6mA
          EKIWZt7+AxG8mzhop0QQDIQFfGY7j6dO2zs5+HuT3XDV1xyWdtaVDcmy9OzSPtAgij8YB
          A35kA5XXxohvwqj0zymJ2BAflKFOANUG+PmbxfqWtUAukox8JGT4Z3larYbOZjV6VqNt/
          R0a9YTMQ0K+Fn770NcFG7X1q4x1+z7uQV76xqXaqzAQZdHAsNh5M7i+zrwTF3tBSE+Eth
          pG1GyVNv+CbDWSMu3xKwLCEP6Xzi/FWyX+UlrOFPrzCMnvKfaUa7S8Nfowh5uM=
        - KKC4U9NAEBukb0+DiOO9/tJQKYUJS9pLRuZVrPglw8ig0lIvKyfUYCeUlCrZdVMiOUUaB
          9ljpKO4Qn7cSQG6muzrFpT8xnZVMioNBJhPBZ53Fv7LaLpMxOLv8SJwoIptkOb8md85Hu
          YTdY70EufcIMvkJ8C1O4uCZmwEl9ydbxcqGmnp7xh6TxD21BzfTanWa/ylHYF3D5xNkK4
          TJ1S/yi7HXHQ4vTO0Tys0s8CVAl7tgK2A0HE9AzOe5DL+V1NwdOC1kNqh4fY3QiVQuNbp
          I5AXgn+DnL/RwG9Et4sOor9eTe7dG+1rARgSmzsxH5pXVKQR+NqCmG63HBwwfYT5XG0fq
          JoLaUQf3DAt2aLCcPx8TNnhZXM0ofFddGXkkf9a42OFwFH0Dh/tL2I8/bhEfyCj1WbA32
          LpvISJg/t1rCVuiOsNSzLWNWNsj5ra5HXI09lgcAk1TAUArxRylfWoIMurWfOH29n9Vmw
          3//ZGIoAFpB5R0BOrQjaQgAI59AWR1AaA5n6XWbu2M4a8f5YvZjQ1TEsffL3bI+ktNH2K
          s5LmBc4X7qCZIgpYDWm+3P4jFJ26ibXaVDiKYGJObbEIDA8iCGsE6yq0DQ/gixdSi+1fR
          XrPQz3SfrOMidrCvQZdNgSQoSgQpSnkwW7W33Hf4KtMufdkiFBhxYeXyhn4rIk=
        - JJViIrfPhojodPbyEj0GRaiKutDb9zNbp38TExwj8IhJwUASeP1d7zMK6MvOQHJ2ewqe1
          V9jITfzJJLoHRVSMuFtkpxyru6ARUw9P0Wg/wIZgCB9UY69fcpu/gsMXCif4qMjigXG08
          glToPuUgmVnYRwYmVESGUYyiaZ50z90SXbOuWSrw1cVXHsIp2T5aUTDClQSe42O+XRtXf
          abLGSY23SHqNckRd3heB4tT+EwIZR3TOpnGgyVp2XDnD4SdOwJS2E+YwxEI7ps9mMwpW8
          kVH7L/4B49nf5kxpm764Kz5b6M4S06ntFGDfjU3/0IP6EC8ULSVB7CVeaJx3YtwBEIvWy
          ClLSfxP5BUdFlnYmHoxeV0ZoKU2vA0fT8ciVM4NmXaT6yq6vDtP3Kypxlq7mMW3n+Rck+
          tbpjQXydhR5BsxgxdICj3c+jDMjjBpW3V7ykfKjzmM12Z0zUTCvi30AJnQlWt7O5A7sGL
          sv8l5uuTuXKjJx2uX8S9TjWsUAwMJSDaT72tBTpGsA2RI437fXdMpX+6AeSeGDnwZMsyI
          IkM54vtwVyH8KWvC98YbGXLcse3y2mA2Ebfi1ta1pVmdKqpgvwplMI6/igKmlk8uEV5zP
          88NsTDU8t1P0Mffp+HE1aHvwDXCJPZoJ4uto5qUvcL4uPTHOfoK+6y8zAIZjE8=
        - UNcl/37qk2NbGllMpEBsCDN1/jjpzMYyjChCMpll42LQzssWX5Wdf7aWmRObTkBd3QMgu
          0STH5gt7QrmYXVjU2lOZPb9fc51IxZiRaVk+t2IVCkWQw8aEJyMtZ50WWggDXxtHK3VIG
          hANLtlmPpy62VPlkOdDEva9rLC5ZCZG5BhhXDDykeCpAnZcH8mcI/iuLKs7EwbeED2+/n
          BGjjZHfvLl8lT4VBRUuHws8/meJ1/Jj3GPXt95uCdeXYsBSD41PYPUKC0+6UqXm1QD/8+
          iwmhrKR9rkk70xJ8BaeUES23tKNBMwhUILkBtGjb3esW8J5aiNzmmejGI3GQ63SVpQqQX
          N2WuYGAr+U6LgfzJ7YqlBOWMJCY+S3QliDbyNVR/lYp1B7SSW2ezjLDRPHUGUamDBW9a2
          Sf3R8ZzF5cAkUpE2m5ne6VuSYBUB8V+WS7V885tRLoODF/kC7Ayk9cPaqvKABWwcfelJ8
          AmLpX8uc30+NJ1nSWQwEbojLKZk3w3VIbeeJrv4bmVNq7qA56kLTn3KyQ/C0Zb8q3N0yi
          321VH4KURtyDm+0Q0OBg0sn4mVH/n1ZjiHBI2FyAiqdZn24/k6mmyLsBP16jab4SyT/EC
          6a+RtBOXr9KC/7Yh15NblPR0+svpySBJVx2nmRacrUKENY/NgfEsLcUSz9FLJQ=
        - ercME5nyuE0QJrO/owvdCaBzXMifvMSatdGieDWAs8rdZVfTt4M4iIKp91BtVJhAkVLup
          Ud+aHXkeoOg4EQiipOyfcSyVOiOjXV2xBss9K76f/PKFwgmnOqiO4W1qgOj4cZLvzxMDv
          NLfhF95i4c6YY9QgQADlT8FtH/tJaMoiP55jYzIq8qaFVQdkSVEtpBmm6Mdw5cGSv0xJF
          rhOWdO3S39srQbXpqL75LMIAXVAmBxLnlNxzRSOI7pdZ7FidgpOmbw/1KgEmMhyRkB0tr
          o3Kdrjma/ngfK4Cvxz0bLCYrUcx2x9h7Gj9FuaDvhXAdJEqiBDVY9evUT5GlTgO8QZJCi
          5A33YXLy2LRPArKVtfk8h1HG62dQwatSdgOjKBcMSlC4/NXqNH+1qpcdYLXr9M3shRry3
          ikge77ZL4D+Fy8PvCLwwTVT4TyvmC4FwZUcdUytp0+BXu28f2fTLZlRMv7iuwqWx88UVV
          hxXbnKkl/z8na6b0wDH3LA/Vbxi14qtLWuA4l3nq1zq9G5XJSz9aeV5Qvdzqj2HyJe01w
          K4iCemHpNHzgsrCx0EWMV6631w1JY2OuZmRjNILGi3V8Qmtas8HaC0pxczWpiGDwLeTK+
          3XOQmVFDY4gjC3Q/n8njIoOOb5n+zObzJLe9FuCNVeLdWRenBd6k9dKTCJ2vtw=
        - P6w2oBb6eEi7/vwZOoPH1ILX8r45mMxWZXxWBMqeE1jpf8ZRGMrnB9tL8AMR/Nr2oDEuz
          JOKuWYKbqYmJsNOa6md5nHLurTg1aTibxohXVNtE5fexeca4BX11F5+BN7nFLWR9W73Uj
          Ky9EV8GDKa8V3fd0jHNDeLsSh1tjYpGYkPGyqRqsMsutjfuTe8ivW9j0KsIHA/aP3/VTs
          X0BA63iIUys/TksvXhePhKv8qxDldClOWY493R+V7zTlLKcLuJJFZrYse9FWaTfHAcdxT
          JMAjjmLnAJCpcD+nLMDh/XDBy0bi9xOjn1KJbii1+oEwvSruwxShwFcLHEKbD+mqazghg
          MeJoOlcDNIaRsgTnANxcA1zhP77iAMgqYudWfrVYfiKg3BTsGhtCvadAqpesTmFhSbPow
          eRnVyFNs2QO93ArzJ1RY2MhSUZtjQTvF+fKbsa0Uwk/bBMRzVlcZXIccea2nahzAyUej4
          FpFZjSqOGBw6MKXSS80PMyZzJ8ySnwUpw7UsZ+9K+6V44GVhwR62U2ce7+x/h971TFaSf
          LULEStq9ZVL3pF+LXtX/gP1vRlHeCjkXhLp64vG9NrPeslb6j83ez1+UG3Pl0F+Wl+n6f
          Qv/mWH5VPpd9yZPVSWQlYKxG3/yL2f1SKq/OQwr1Ip58mD1rF3RYBvkMllGAeM=
