#!/bin/bash

set -x

PKG_BUILD_NAME=$1
PKG_BUILD_DIR=$(realpath `pwd`/${PKG_BUILD_NAME})

STX_BASE=$(realpath ${MY_REPO}/stx)
PKG_BASE=$(realpath ${STX_BASE}/distributedcloud-client/distributedcloud-client)

mkdir ${PKG_BUILD_NAME}

cp -r ${PKG_BASE}/* ${PKG_BUILD_DIR}/
